"""create chatresponse table

Revision ID: b41701a613b4
Revises: 471984bd103e
Create Date: 2024-09-20 12:14:47.642328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41701a613b4'
down_revision: Union[str, None] = '471984bd103e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatresponse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('content_type', sa.Integer(), nullable=True),
    sa.Column('language_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_type'], ['contenttype.id'],name="fk_chatresponse_content_type_contenttype_id" ),
    sa.ForeignKeyConstraint(['language_type'], ['languages.id'], name="fk_chatresponse_language_type_languages_id"),
    sa.ForeignKeyConstraint(['prompt_id'], ['chatprompt.id'],name="fk_chatresponse_prompt_id_chatprompt_id" ),
    sa.PrimaryKeyConstraint('id',name="pk_chatresponse_id")
    )
    op.create_index(op.f('ix_chatresponse_prompt_id'), 'chatresponse', ['prompt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatresponse_prompt_id'), table_name='chatresponse')
    op.drop_table('chatresponse')
    # ### end Alembic commands ###
