"""add isdelete column in chatprompt table

Revision ID: 20554065197e
Revises: b41701a613b4
Create Date: 2024-09-20 15:45:29.297667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20554065197e'
down_revision: Union[str, None] = 'b41701a613b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatprompt', sa.Column('isdeleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatprompt', 'isdeleted')
    # ### end Alembic commands ###
