"""create user table

Revision ID: a8ee030e9e9d
Revises: a7b420aa81e8
Create Date: 2024-09-20 12:07:24.418556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ee030e9e9d'
down_revision: Union[str, None] = 'a7b420aa81e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('isdeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['userrole.id'], name="fk_user_role_userrole_id"),
    sa.PrimaryKeyConstraint('id',name="pk_user_id")
    )
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
