"""add lang_code  column in languages table

Revision ID: a2980a4fb8cc
Revises: 20554065197e
Create Date: 2024-09-24 12:32:27.640610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2980a4fb8cc'
down_revision: Union[str, None] = '20554065197e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('lang_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.drop_column('languages', 'lang_code')
    # ### end Alembic commands ###
